# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('email_address', models.EmailField(max_length=45, unique=True)),
                ('street_address', models.TextField()),
                ('phone', models.CharField(max_length=14)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='logo_images', verbose_name='Upload a logo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
