# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20160722_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images', verbose_name='Upload a photo'),
        ),
    ]
