# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 18:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0004_auto_20160729_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yardsale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regular_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Listing')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('special_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.SpecialSale')),
            ],
        ),
    ]
