# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 18:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_yardsale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yardsale',
            name='regular_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.Listing'),
        ),
        migrations.AlterField(
            model_name='yardsale',
            name='special_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.SpecialSale'),
        ),
    ]
