# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20160801_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialsale',
            name='category',
        ),
        migrations.RemoveField(
            model_name='specialsale',
            name='seller',
        ),
        migrations.AlterModelOptions(
            name='yardsale',
            options={'ordering': ['-created']},
        ),
        migrations.RemoveField(
            model_name='listing',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='yardsale',
            name='regular_sale',
        ),
        migrations.RemoveField(
            model_name='yardsale',
            name='special_sale',
        ),
        migrations.AddField(
            model_name='listing',
            name='yardsale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.Yardsale'),
        ),
        migrations.AddField(
            model_name='yardsale',
            name='cause',
            field=models.CharField(choices=[('Extra fun', 'Extra fun'), ('Personal need', 'Personal need'), ('Big trip', 'Big trip'), ('Help others', 'Help others'), ('Other', 'Other')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='yardsale',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='yardsale',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='yardsale',
            name='name',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='yardsale',
            name='sale_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.DeleteModel(
            name='SpecialSale',
        ),
    ]
