# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20160801_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='item',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
