# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20160801_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='yardsale',
            name='name',
            field=models.CharField(blank=True, default='', max_length=35),
        ),
    ]
